const KEY='pandaagua_v03';
const defaultState={people:{juliana:{name:'Juliana',goal:2000},eber:{name:'Éber',goal:2000}},logs:[]};
let state=load();let current='juliana';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function addWater(ml){state.logs.push({id:crypto.randomUUID(),personId:current,ml,date:today(),timestamp:new Date().toISOString()});save();render();const t=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});status(`🐼 ${state.people[current].name} registrou ${ml} ml às ${t}.`)}
function personTotal(id){return state.logs.filter(x=>x.personId===id&&x.date===today()).reduce((a,x)=>a+x.ml,0)}
function render(){const p=state.people[current],total=personTotal(current),pct=Math.min(100,Math.round(total/p.goal*100));document.querySelector('#personLabel').textContent=p.name;document.querySelector('#total').textContent=`${total.toLocaleString('pt-BR')} ml`;document.querySelector('#pct').textContent=`${pct}%`;const deg=pct*3.6;document.querySelector('#ring').style.background=`conic-gradient(#60a5fa 0deg ${deg}deg,#e5e7eb ${deg}deg 360deg)`;document.querySelector('#message').innerHTML=total>=p.goal?'🎉 Meta atingida! O panda está orgulhoso! 🐼':`Faltam <strong>${Math.max(0,p.goal-total).toLocaleString('pt-BR')} ml</strong> para a meta 🐼`;document.querySelector('#goal').value=p.goal;const todayLogs=state.logs.filter(x=>x.personId===current&&x.date===today()).sort((a,b)=>b.timestamp.localeCompare(a.timestamp));document.querySelector('#count').textContent=`${todayLogs.length} registro${todayLogs.length===1?'':'s'}`;document.querySelector('#logs').innerHTML=todayLogs.length?todayLogs.map(x=>{const t=new Date(x.timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});return `<div class="row"><span>🕘 ${t}</span><strong>${x.ml} ml</strong></div>`}).join(''):'<span class="muted">Nenhum registro ainda.</span>';const j=personTotal('juliana'),e=personTotal('eber');document.querySelector('#jtxt').textContent=`${j.toLocaleString('pt-BR')} / ${state.people.juliana.goal.toLocaleString('pt-BR')} ml`;document.querySelector('#etxt').textContent=`${e.toLocaleString('pt-BR')} / ${state.people.eber.goal.toLocaleString('pt-BR')} ml`;document.querySelector('#jbar').max=state.people.juliana.goal;document.querySelector('#jbar').value=j;document.querySelector('#ebar').max=state.people.eber.goal;document.querySelector('#ebar').value=e;document.querySelector('#couple').textContent=`${(j+e).toLocaleString('pt-BR')} / ${(state.people.juliana.goal+state.people.eber.goal).toLocaleString('pt-BR')} ml juntos`}
function status(t){document.querySelector('#status').textContent=t}
document.querySelector('#person').addEventListener('change',e=>{current=e.target.value;render()});document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addWater(Number(b.dataset.add))));document.querySelector('#other').addEventListener('click',()=>{const v=Number(prompt('Quantos ml você tomou?'));if(Number.isFinite(v)&&v>0&&v<=5000)addWater(Math.round(v))});document.querySelector('#saveGoal').addEventListener('click',()=>{const v=Number(document.querySelector('#goal').value);if(v>=500&&v<=10000){state.people[current].goal=Math.round(v);save();render();status(`🎯 Meta de ${Math.round(v).toLocaleString('pt-BR')} ml salva para ${state.people[current].name}.`)}});render();
